# Set a plain language title for the site.
title: USWDS Design Tokens Guide

# Write a short description for the site. This is used for "meta description."
description: Guidance on how designers can progressively understand and apply the use of design tokens in their work

# Set the language for the site. Used for "html lang." Default is English.
lang: en

# Add Google Analytics if needed. Replace placeholder with site ID.
ga: UA-XXXXX-Y

# Avoid GitHub API authentication when building locally. (Not working)
github: [metadata]

# Enable for live hosting on GitHub Pages
baseurl: /uswds-design-tokens-guide

# Remove generation of additional style.css
theme: null

# Global content
logo: assets/img/bixal-logo-full.svg
logo-alt-text: "The Bixal logotype is cleancut and powerful."
tel: "+17036345701"
tel-display: "+1 703 634 5701"
email: info@bixal.com